accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('cadastro/', views.add_user_register, name='add_user_register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('alterar-senha/', views.user_change_password, name='user_change_password'),
    path('novo-perfil/', views.add_user_profile, name='add_user_profile'),
    path('perfil/', views.list_user_profile, name='list_user_profile'),
    path('alterar-perfil/<username>/', views.change_user_profile, name='change_user_profile'),
    path('alterar-cadastro/<username>/', views.change_user_information, name='change_user_information'),
]

clickpublique/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('accounts.urls', namespace='accounts')),
    path('lojas/', include('woocommerce.urls', namespace='woocommerce')),
    path('', include('core.urls', namespace='core')),
]

#Uploads/Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from . import views
from django.urls import path

app_name = 'core'


urlpatterns = [
    #path('buscar', views.search_tasks, name='search_tasks'),
    path('', views.home, name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from uuid import uuid4
from datetime import datetime
import os
import random


# Create your models here.

def photo_path(instance, filename):
    basefilename, file_extension= os.path.splitext(filename)
    chars= 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr= ''.join((random.choice(chars)) for x in range(50))
    #return 'images/userphotos/{userid}/{basename}{randomstring}{ext}'.format(userid= instance.user.id, basename= basefilename, randomstring= randomstr, ext= file_extension)
    return 'accounts/'+'{userid}{randomstring}{ext}'.format(userid= instance.user.id, basename= basefilename, randomstring=randomstr, ext=file_extension)


class UserProfile(models.Model):
    #upload_dir = uuid4().hex
    #upload_dir += datetime.datetime.now()
    #photo = models.ImageField('Foto', upload_to=upload_dir)
    photo = models.ImageField('Foto', upload_to=photo_path, null=True)
    cell_phone = models.CharField('Celular', max_length=16)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    #Update and Create
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Perfil do usuário'
        verbose_name_plural = 'Perfis dos usuários'

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password', 'email']
        labels = {
            "last_name": "Sobrenome"
        }

class UserFormChangeInformation(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {
            "last_name": "Sobrenome"
        }

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import UserForm, UserProfileForm, UserFormChangeInformation
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from .models import UserProfile
from django.core.exceptions import MultipleObjectsReturned
from django.http import HttpResponseRedirect
from django.db import IntegrityError
import os, stat
import shutil

def add_user_register(request):
    template_name = 'add_user_register.html'
    context = {}
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
            messages.success(request, 'Criado com sucesso!')
            return HttpResponseRedirect('/')
    form = UserForm()
    context['form'] = form
    return render(request, template_name, context)

def user_login(request):
    template_name = 'user_login.html'
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login efetuado com sucesso!')
            return redirect(request.GET.get('next', '/'))
            #return HttpResponseRedirect(request.POST.get('next'))
        else:
            messages.error(request, 'Usuário ou senha inválidos')
    return render(request, template_name, {})

@login_required(login_url='/usuarios/login/')
def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')

@login_required(login_url='/usuarios/login/')
def user_change_password(request):
    template_name = 'user_change_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():            
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Senha modificada com sucesso!')
        else:
            messages.error(request, 'Não foi possível modificar sua senha')
    form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/usuarios/login/')
def add_user_profile(request):    
    template_name = 'add_user_profile.html'
    context = {}
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        try:
            if form.is_valid():                
                f = form.save(commit=False)
                f.user = request.user
                f.save()
                messages.success(request, 'Modificado com sucesso!')
                return redirect('accounts:list_user_profile')
        except MultipleObjectsReturned:
            messages.error(request, 'Já existe um perfil!')
        except IntegrityError:
            messages.error(request, 'Você já tem um perfil cadastrado!')
    form = UserProfileForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/usuarios/login/')
def list_user_profile(request):
    template_name = 'list_user_profile.html'
    return render(request, template_name, {})

@login_required(login_url='/usuarios/login/')
def change_user_profile(request, username):
    template_name = 'add_user_profile.html'
    context = {}
    profile = UserProfile.objects.get(user__username=username)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        #Remove archive old photo
        
        #old_profile.photo.delete(save=False)
        #print(old_profile.__dict__)
        #shutil.rmtree('/folder_name', ignore_errors=True)
        #file_path = old_profile.photo
        #print(os.path.join("sdfsdfsdf"))
        if form.is_valid():
            f = form.save(commit=False)            
            if(request.FILES.get('photo')):
                old_profile = UserProfile.objects.get(pk=form.initial['id'])
                old_profile.photo.delete(save=False)          
            f.save()
            messages.success(request, 'Modificado com sucesso!')
    form = UserProfileForm(instance=profile)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/usuarios/login/')
def change_user_information(request, username):
    template_name = 'change_user_information.html'
    context = {}
    user = User.objects.get(username=username)
    if request.method == 'POST':
        form = UserFormChangeInformation(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Modificado com sucesso!')
    form = UserFormChangeInformation(instance=user)
    context['form'] = form
    return render(request, template_name, context)

accounts/templates/add_user_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
    Alterar perfil - {{ block.super }}
{% endblock title %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Perfil</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">Perfil</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    
    <!-- Main content -->
    <section class="content">
    
        <!-- Default box -->
        <div class="card">
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <form action="." method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                
                            <div class="form-group">
                                <label for="{{ form.photo.id_for_label }}">{{ form.photo.label_tag }}</label>
                                {{ form.photo|add_class:"form-control-file" }}
                            </div>
                
                            <div class="form-group">
                                <label for="{{ form.cell_phone.id_for_label }}">{{ form.cell_phone.label_tag }}</label>
                                {{ form.cell_phone|add_class:"form-control" }}
                            </div>
                
                            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
                            <a href="/" class="btn btn-secondary float-right">
                                <i class="nav-icon fa fa-list-ul"></i>
                            </a>
                
                        </form>
                
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    
    </section>
    <!-- /.content -->
    
{% endblock content %}

accounts/templates/add_user_register.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Registration Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="https://adminlte.io/themes/v3/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="https://adminlte.io/themes/v3/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />


</head>


<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo mt-2">
            <img src="{% static 'img/logo/logo-clickpublique-fundo-transp-horizontal.png' %}" alt="" width="300px">
        </div>

        <div class="card">
            <div class="card-body register-card-body">
                <p class="login-box-msg">Criar uma Conta</p>

                {% include 'partials/messages.html' %}

                <form action="." method="post">
                    {% csrf_token %}
                    <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label_tag }}</label>
                    <div class="input-group mb-3">
                        
                        {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label_tag }}</label>
                    <div class="input-group mb-3">
                        {{ form.last_name|add_class:"form-control" }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label_tag }}</label>
                    <div class="input-group mb-3">
                        {{ form.username|add_class:"form-control" }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label_tag }}</label>
                    <div class="input-group mb-3">
                        {{ form.email|add_class:"form-control" }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <label for="{{ form.email.id_for_label }}">{{ form.password.label_tag }}</label>
                    <div class="input-group mb-3">
                        {{ form.password|add_class:"form-control"|attr:"type:password" }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">  
                        <div class="col-12 mt-2 mb-2">
                            <div class="icheck-primary">
                                <input type="checkbox" id="agreeTerms" name="terms" value="agree" required >
                                <label for="agreeTerms">
                                    Concordo com os <a href="#">termos</a>
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->

                        <div class="col-12">
                            <button type="submit" class="btn btn-dark btn-block">
                                <i class="fa fa-save"></i> Cadastrar
                            </button>
                        </div>
                        <!-- /.col -->
                        
                    </div>
                </form>

                <br><br>

                <a href="/" class="btn btn-secondary btn-xs float-right">
                    <i class="fas fa-sign-in-alt"></i>
                    Já possuo um cadastro.
                </a>
            </div>
            <!-- /.form-box -->
        </div><!-- /.card -->
    </div>
    <!-- /.register-box -->

    <!-- jQuery -->
    <script src="https://adminlte.io/themes/v3/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="https://adminlte.io/themes/v3/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://adminlte.io/themes/v3/dist/js/adminlte.min.js"></script>

    
    <script type="text/javascript">
        $(document).ready(function () {
            $("#container-messages").removeClass("fade show");
        });
    </script>
</body>

</html>

accounts/templates/change_user_information.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
    Perfil - {{ block.super }}
{% endblock title %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Perfil</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">Perfil</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">

            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <form action="." method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.first_name.id_for_label }}">Primeiro Nome:</label>
                                {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.last_name.id_for_label }}">Último Nome:</label>
                                {{ form.last_name|add_class:"form-control" }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.email.id_for_label }}">e-mail:</label>
                                {{ form.email|add_class:"form-control" }}
                            </div>
                            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
                            <a href="/" class="btn btn-secondary float-right">
                                <i class="nav-icon fa fa-list-ul"></i>
                            </a>
                
                        </form>
                
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->


{% endblock content %}

accounts/templates/list_user_profile.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Perfil - {{ block.super }}
{% endblock title %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Perfil</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">Perfil</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">

            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 mx-auto">
                        
                
                        {% if user.profile %}
                
                        <!-- Profile Image -->
                        <div class="card card-outline">
                            <div class="card-body box-profile">
                                <div class="text-center">
                                    {% if user.profile.photo %}
                                    <img class="profile-user-img img-fluid img-circle" src="{{ user.profile.photo.url }}"
                                        alt="User profile picture">
                                    {% else %}
                                    <img class="profile-user-img img-fluid img-circle" src="{% static 'img/profile.png' %}"
                                        alt="User profile picture">
                                    {% endif %}
                
                                </div>
                
                                <h3 class="profile-username text-center">{{ user.get_full_name|default:user.username }}</h3>
                
                                <p class="text-muted text-center">{{ user.get_full_name|default:user.username }}</p>
                
                
                
                
                            </div>
                            <!-- /.card-body -->
                
                            <div class="card-header">
                                <h3 class="card-title">Sobre mim</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <strong><i class="fas fa-chevron-circle-right mr-1"></i> Nome Completo</strong>
                
                                <p class="text-muted">
                                    {{ user.get_full_name|default:'--' }}
                                </p>
                
                                <hr>
                
                                <strong><i class="fas fa-chevron-circle-right mr-1"></i> Celular</strong>
                
                                <p class="text-muted">
                                    {{ user.profile.cell_phone|default:'--' }}
                                </p>
                
                                <hr>
                
                                <strong><i class="fas fa-chevron-circle-right mr-1"></i> e-mail</strong>
                
                                <p class="text-muted">
                                    {{ user.email|default:'--' }}
                                </p>
                
                                <hr>
                
                                <a href="{% url 'accounts:change_user_profile' user.username %}"
                                    class="col-md-3 mx-auto btn btn-primary btn-block">
                                    <i class="fa fa-edit"></i>
                                    <b>Alterar Perfil</b>
                                </a>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                
                        {% else %}
                
                        <!-- Profile Image -->
                        <div class="card card-outline">
                            <div class="card-body box-profile">
                                <h3 class="profile-username text-center">Não existe perfil</h3>
                
                                <a href="{% url 'accounts:add_user_profile' %}" class="col-md-3 mx-auto btn btn-primary btn-block">
                                    <i class="fa fa-edit"></i>
                                    <b>Criar Perfil</b>
                                </a>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                
                        {% endif %}
                
                        <!-- Profile Image -->
                        <div class="card card-outline">
                
                            <!-- /.card-header -->
                            <div class="card-body">
                                <a href="{% url 'accounts:change_user_information' user.username %}"
                                    class="col-md-3 mx-auto btn btn-secondary btn-block">
                                    <i class="fa fa-edit"></i>
                                    <b>Alterar Cadastro</b>
                                </a>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                
                
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->

{% endblock content %}

accounts/templates/user_login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>ClickPublique</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    
    <!-- Custom styles for this template -->
    <style type="text/css" rel="stylesheet">
        html,
        body {
        height: 100%;
        }

        body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
        }

        .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
        }
        .form-signin .checkbox {
        font-weight: 400;
        }
        .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
        }
        .form-signin .form-control:focus {
        z-index: 2;
        }
        .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        }
    </style>
</head>

<body class="text-center">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#container-messages").removeClass("fade show");
        });
    </script>
    <form class="form-signin" method="POST" action=".">
        {% csrf_token %}        
        <img class="mb-4" src="{% static 'img/logo/logo-clickpublique-fundo-transp-horizontal.png' %}" alt="" width="300px">        
        <h1 class="h3 mb-3 font-weight-normal" id="h1-login">Login</h1>
        {% include 'partials/messages.html' %}
        <label for="username" class="sr-only">Usuário</label>
        <input type="text" id="username" class="form-control" placeholder="Usuário" name="username" required autofocus>
        <label for="password" class="sr-only">Senha</label>
        <input type="password" id="password" class="form-control" placeholder="Senha" name="password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Lembrar
            </label>
        </div>        
        <button class="btn btn-lg btn-dark btn-block" type="submit">Entrar</button>
        <br>
        <a href="{% url 'accounts:add_user_register' %}" class="btn btn-sm btn-secondary btn-block">Criar Conta</a>
        <br>
        <p class="mt-5 mb-3 text-muted">&copy; ClickPublique.com 2020</p>
    </form>
    
</body>

</html>