accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('cadastro/', views.add_user_register, name='add_user_register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('alterar-senha/', views.user_change_password, name='user_change_password'),
    path('novo-perfil/', views.add_user_profile, name='add_user_profile'),
    path('perfil/', views.list_user_profile, name='list_user_profile'),
    path('alterar-perfil/<username>/', views.change_user_profile, name='change_user_profile'),
    path('alterar-cadastro/<username>/', views.change_user_information, name='change_user_information'),
]

clickpublique/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('accounts.urls', namespace='accounts')),
    path('lojas/', include('woocommerce.urls', namespace='woocommerce')),
    path('', include('core.urls', namespace='core')),
]

#Uploads/Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from . import views
from django.urls import path

app_name = 'core'


urlpatterns = [
    #path('buscar', views.search_tasks, name='search_tasks'),
    path('', views.home, name='home'),
]

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/usuarios/login/')
def home(request):
    return render(request, 'base.html', {}) 

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Click e Publique{% endblock title %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">

            

            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>        
            
            <!-- SEARCH FORM -->
            {% block search %}
            <form class="form-inline ml-3" action="#" method="GET">
                <div class="input-group input-group-sm">
                    <input name="query" disabled value="{{ param_search|default:'' }}" class="form-control form-control-navbar"
                        type="search" placeholder="Buscar" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit" disabled>
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            {% endblock %}
        
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
        
                {% if user.is_authenticated %}
                
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fa fa-user"></i>
                        <!--<span class="badge badge-warning navbar-badge">15</span>-->
                    </a>
                    <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">

                        {% if user.is_authenticated %}
                        <span class="dropdown-item dropdown-header">{{ user.get_first_name|default:user.username }}</span>
                        {% else %}
                        <span class="dropdown-item dropdown-header">Convidado</span>
                        {% endif %}
                        
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'accounts:list_user_profile' %}" class="dropdown-item">
                            <i class="fa fa-id-card mr-2"></i> Perfil                           
                        </a>

                        <div class="dropdown-divider"></div>
                        <a href="{% url 'accounts:user_change_password' %}" class="dropdown-item">
                            <i class="fa fa-key mr-2"></i> Senha
                        </a>

                        <div class="dropdown-divider"></div>
                        <a href="{% url 'accounts:user_logout' %}" class="dropdown-item">
                            <i class="fas fa-power-off mr-2"></i> Sair
                        </a>

                    </div>
                </li>

                {% endif %}
                
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="{% static 'img/logo/logo-mini-128x128.png' %}" alt="clickpublique Logo" class="brand-image img-circle elevation-3"
                    style="opacity: .8">
                <span class="brand-text font-weight-light">click<b>publique</b></span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">                    
                        {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}" class="rounded-circle" alt="User Image">
                        {% else %}
                        <img src="{% static 'img/profile.png' %}" class="img-circle elevation-2" alt="User Image" width="90" height="90">
                        {% endif %}                    
                    </div>
                    <div class="info">
                        {% if user.is_authenticated %}
                        <a href="#" class="d-block">
                            {{ user.get_first_name|default:user.username }}
                        </a>
                        {% else %}
                        <p>Convidado</p>
                        {% endif %}
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class -->
                        <!-- with font-awesome or any other icon font library -->                          
                        <li class="nav-item">
                            <a href="lojas" class="nav-link">
                            <i class="nav-icon fa fa-store"></i>
                            <p>
                                Lojas
                                <span class="right badge badge-danger">New</span>
                            </p>
                            </a>
                        </li>                      
                        
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->            
        </aside>

        

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">            
            {% include 'partials/messages.html' %}      
            {% block content %}
            {% endblock content %}
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2020 <a href="http://clickpublique.com">ClickPublique.com</a>.</strong>
           Todos os direitos reservados.        
            <div class="float-right d-none d-sm-inline-block">                
                <b>Version</b> 1<a href="admin" target="_blank">.</a>0.1
            </div>
            
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- modals -->
    {% include 'partials/modals.html' %}
    <!-- ./modals -->

    <!-- jQuery -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'AdminLTE-3.0.4/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'AdminLTE-3.0.4/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'AdminLTE-3.0.4/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'AdminLTE-3.0.4/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'AdminLTE-3.0.4/dist/js/pages/dashboard.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'AdminLTE-3.0.4/dist/js/demo.js' %}"></script>

    <!-- Modal Scripts -->
    <script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/masks.js' %}"></script>
</body>

</html>